### ISSUE TITLE
database_logger_sink::flush()

### ISSUE THREAD

**Issue by tahazayed** [PedroRod/sqlite3_database_sink#1]
I got this error
include/sqlite_sink.h: In destructor ‘virtual spdlog::sinks::sqlite_sink::~sqlite_sink()’:
include/sqlite_sink.h:27:5: error: ‘database_logger_sink’ has not been declared
     database_logger_sink::flush();
     ^~~~~~~~~~~~~~~~~~~~

**Comment by PedroRod** [comment]
Please, Use this code snippet as a starting point.

```#include "SQLite.h"
int main()
{
	try{
		SQLite::Database db("test.db");

		SQLite::Statement statement(db, "select * from User");

		while (statement.NextRow())
		{
			std::string lastName = statement.GetColumn("LastName");

			// Code Logic
		}
	}
	catch (std::exception& ex)
	{
		//handle error
	}
}

**Comment by tahazayed** [comment]
it works after changing database_logger_sink::flush(); to sqlite_sink::flush();
